### ISSUE TITLE
Scverse discourse forum

### ISSUE THREAD

**Issue by adamgayoso** [scverse/governance#23]
We agreed today to set up a joint discourse for scverse. In this issue we can track TODOs, and discuss the structure/logistics.

- [ ]  Create scverse discourse (#24)
- [ ] Structure the forum (#25)
- [ ] Decide and provide appropriate permissions to individuals (#26)

**Comment by grst** [comment]
I think we can close this as well?
